// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Migrations run against Supabase's direct (non-pooled) connection —
// Supavisor's transaction pooler (DATABASE_URL, used by the app at runtime)
// doesn't reliably support the prepared statements Prisma's migration engine
// needs. See DEVIATIONS.md / README for the two-URL Supabase setup.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node --transpile-only prisma/seed.ts",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
