import { Prisma } from '../../generated/prisma';

// Fixed closed set of solicitud estados (`EstadoSolicitud.nombre` in the DB
// — see schema.prisma / DEVIATIONS.md). Written by hand instead of
// generated by Prisma since `EstadoSolicitud` is a lookup table, not an
// enum. `nombre` stores the human label directly (e.g. "En curso") — unlike
// the old Postgres enum, there's no identifier/label split to translate
// anymore.
export const ESTADO_NOMBRES = [
  'Activa',
  'Aprobado',
  'En curso',
  'Finalizada',
  'No aprobado',
  'Cancelada',
] as const;
export type EstadoNombre = (typeof ESTADO_NOMBRES)[number];

export const STATUS_LABELS: readonly string[] = ESTADO_NOMBRES;

// 'Aprobado' is still pending completion (HC approved the move but it
// hasn't happened yet) so it counts as open the same as 'Activa'/'En curso'
// — it still blocks a duplicate request to the same sucursal.
export const OPEN_STATUSES: EstadoNombre[] = ['Activa', 'Aprobado', 'En curso'];

export const STATUS_ORDER: EstadoNombre[] = [
  'Activa',
  'Aprobado',
  'En curso',
  'Finalizada',
  'No aprobado',
  'Cancelada',
];

// Matches the frontend's `STATUS_DOT_COLORS`/`STATUS_STYLES`
// (src/data/constants.ts) exactly, since the pie chart currently sources
// color straight from the data layer.
export const STATUS_COLOR: Record<EstadoNombre, string> = {
  Activa: '#0284C7',
  Aprobado: '#7C3AED',
  'En curso': '#D97706',
  Finalizada: '#1F7A4D',
  'No aprobado': '#DC2626',
  Cancelada: '#78716C',
};

// A solicitud's current estado is NOT a stored field — per the approved
// diagram (see DEVIATIONS.md §9), it's the `CambioEstadoSolicitud` row for
// that solicitud with `fechaFin IS NULL`. This include/helper pair is the
// one place that lookup is expressed, shared by every service that needs a
// solicitud's current status.
export const CURRENT_ESTADO_INCLUDE = {
  historial: {
    where: { fechaFin: null },
    take: 1,
    include: { estado: true },
  },
} satisfies Prisma.SolicitudInclude;

export function currentEstadoNombre(solicitud: {
  historial: { estado: { nombre: string } }[];
}): string {
  const current = solicitud.historial[0];
  if (!current) {
    throw new Error('Solicitud sin estado vigente (historial vacío).');
  }
  return current.estado.nombre;
}

export function formatDateEsAr(date: Date): string {
  return date.toLocaleDateString('es-AR', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    timeZone: 'America/Argentina/Buenos_Aires',
  });
}

// Same as formatDateEsAr but with hour:minute, for the solicitud's
// estado-change timeline where the time of day (not just the day) matters.
// Date and time are formatted separately and joined with " · " (middle dot)
// instead of the locale's default ", " separator — a frontend design call.
export function formatDateTimeEsAr(date: Date): string {
  const datePart = formatDateEsAr(date);
  const timePart = date.toLocaleTimeString('es-AR', {
    hour: '2-digit',
    minute: '2-digit',
    timeZone: 'America/Argentina/Buenos_Aires',
  });
  return `${datePart} · ${timePart}`;
}
