import { Prisma } from '../../generated/prisma';

// Fixed closed set of solicitud estados (`EstadoSolicitud.nombre` in the DB
// — see schema.prisma / DEVIATIONS.md). Written by hand instead of
// generated by Prisma since `EstadoSolicitud` is a lookup table, not an
// enum. `nombre` stores the human label directly (e.g. "En curso") — unlike
// the old Postgres enum, there's no identifier/label split to translate
// anymore.
export const ESTADO_NOMBRES = [
  'Activa',
  'En curso',
  'Cancelada',
  'Finalizada',
] as const;
export type EstadoNombre = (typeof ESTADO_NOMBRES)[number];

export const STATUS_LABELS: readonly string[] = ESTADO_NOMBRES;

export const OPEN_STATUSES: EstadoNombre[] = ['Activa', 'En curso'];

export const STATUS_ORDER: EstadoNombre[] = [
  'Activa',
  'En curso',
  'Finalizada',
  'Cancelada',
];

// Matches the frontend's `STATUS_DATA` colors (src/data/mockData.ts) exactly,
// since the pie chart currently sources color straight from the data layer.
export const STATUS_COLOR: Record<EstadoNombre, string> = {
  Activa: '#0284C7',
  'En curso': '#D97706',
  Finalizada: '#1F7A4D',
  Cancelada: '#78716C',
};

// A solicitud's current estado is NOT a stored field — per the approved
// diagram (see DEVIATIONS.md §9), it's the `CambioEstadoSolicitud` row for
// that solicitud with `fechaFin IS NULL`. This include/helper pair is the
// one place that lookup is expressed, shared by every service that needs a
// solicitud's current status.
export const CURRENT_ESTADO_INCLUDE = {
  historial: {
    where: { fechaFin: null },
    take: 1,
    include: { estado: true },
  },
} satisfies Prisma.SolicitudInclude;

export function currentEstadoNombre(solicitud: {
  historial: { estado: { nombre: string } }[];
}): string {
  const current = solicitud.historial[0];
  if (!current) {
    throw new Error('Solicitud sin estado vigente (historial vacío).');
  }
  return current.estado.nombre;
}

export function formatDateEsAr(date: Date): string {
  return date.toLocaleDateString('es-AR', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    timeZone: 'America/Argentina/Buenos_Aires',
  });
}
