// Fixed closed set of solicitud estados (`EstadoSolicitud.nombre` in the DB
// — see schema.prisma / DEVIATIONS.md). Written by hand instead of
// generated by Prisma since `EstadoSolicitud` is a lookup table, not an
// enum. `nombre` stores the human label directly (e.g. "En curso") — unlike
// the old Postgres enum, there's no identifier/label split to translate
// anymore.
export const ESTADO_NOMBRES = [
  'Activa',
  'En curso',
  'Cancelada',
  'Finalizada',
] as const;
export type EstadoNombre = (typeof ESTADO_NOMBRES)[number];

export const STATUS_LABELS: readonly string[] = ESTADO_NOMBRES;

export const OPEN_STATUSES: EstadoNombre[] = ['Activa', 'En curso'];

export const STATUS_ORDER: EstadoNombre[] = [
  'Activa',
  'En curso',
  'Finalizada',
  'Cancelada',
];

// Matches the frontend's `STATUS_DATA` colors (src/data/mockData.ts) exactly,
// since the pie chart currently sources color straight from the data layer.
export const STATUS_COLOR: Record<EstadoNombre, string> = {
  Activa: '#0284C7',
  'En curso': '#D97706',
  Finalizada: '#1F7A4D',
  Cancelada: '#78716C',
};

export function formatDateEsAr(date: Date): string {
  return date.toLocaleDateString('es-AR', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    timeZone: 'America/Argentina/Buenos_Aires',
  });
}
