// Fixed closed set of colaborador roles (`Rol.nombre` in the DB — see
// schema.prisma / DEVIATIONS.md). Written by hand instead of generated by
// Prisma since `Rol` is a lookup table, not an enum; guards/decorators
// compare these strings directly, no id lookups involved.
export const ROLE_NAMES = ['collaborator', 'hc', 'dt'] as const;
export type Role = (typeof ROLE_NAMES)[number];

export interface AuthenticatedUser {
  id: string;
  legajo: string;
  fullName: string;
  role: Role;
  email: string;
}
